// <auto-generated />
using System;
using Licensing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Licensing.Infrastructure.Migrations
{
    [DbContext(typeof(LicensingDbContext))]
    [Migration("20260921171415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Licensing.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ExternalCustomerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalCustomerId")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AutoRenewal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpirationDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LicenseKeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("LicenseKeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("MaxActivations")
                        .HasColumnType("int");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidFromUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseKeyPrefix");

                    b.HasIndex("PlanId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("CustomerId", "ProductId");

                    b.ToTable("Licenses", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.LicenseActivation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InstanceIdentifier")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastValidatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductVersion")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId", "InstanceIdentifier", "Status");

                    b.ToTable("LicenseActivations", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.LicenseAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("Actor")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("LicenseAuditLogs", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.LicenseFeature", b =>
                {
                    b.Property<Guid>("LicenseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductFeatureId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LimitValue")
                        .HasColumnType("longtext");

                    b.HasKey("LicenseId", "ProductFeatureId");

                    b.HasIndex("ProductFeatureId");

                    b.ToTable("LicenseFeatures", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.LicenseLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LimitKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("LimitValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId", "LimitKey")
                        .IsUnique();

                    b.ToTable("LicenseLimits", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.LicenseStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.ToTable("LicenseStatusHistory", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DefaultDurationDays")
                        .HasColumnType("int");

                    b.Property<int>("DefaultMaxActivations")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Code")
                        .IsUnique();

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.PlanFeature", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductFeatureId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LimitValue")
                        .HasColumnType("longtext");

                    b.HasKey("PlanId", "ProductFeatureId");

                    b.HasIndex("ProductFeatureId");

                    b.ToTable("PlanFeatures", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.ProductFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "FeatureKey")
                        .IsUnique();

                    b.ToTable("ProductFeatures", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CurrentLicenseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpirationDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("longtext");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLicenseId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PlanId");

                    b.HasIndex("ProductId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.SubscriptionRenewal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("NewExpirationUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PreviousExpirationUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RenewedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RenewedBy")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionRenewals", (string)null);
                });

            modelBuilder.Entity("Licensing.Domain.Entities.License", b =>
                {
                    b.HasOne("Licensing.Domain.Entities.Customer", "Customer")
                        .WithMany("Licenses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licensing.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licensing.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licensing.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Licenses")
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("Customer");

                    b.Navigation("Plan");

                    b.Navigation("Product");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.LicenseActivation", b =>
                {
                    b.HasOne("Licensing.Domain.Entities.License", "License")
                        .WithMany("Activations")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.LicenseFeature", b =>
                {
                    b.HasOne("Licensing.Domain.Entities.License", "License")
                        .WithMany("LicenseFeatures")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licensing.Domain.Entities.ProductFeature", "ProductFeature")
                        .WithMany()
                        .HasForeignKey("ProductFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");

                    b.Navigation("ProductFeature");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.LicenseLimit", b =>
                {
                    b.HasOne("Licensing.Domain.Entities.License", "License")
                        .WithMany("LicenseLimits")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.LicenseStatusHistory", b =>
                {
                    b.HasOne("Licensing.Domain.Entities.License", "License")
                        .WithMany("StatusHistory")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.Plan", b =>
                {
                    b.HasOne("Licensing.Domain.Entities.Product", "Product")
                        .WithMany("Plans")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.PlanFeature", b =>
                {
                    b.HasOne("Licensing.Domain.Entities.Plan", "Plan")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licensing.Domain.Entities.ProductFeature", "ProductFeature")
                        .WithMany()
                        .HasForeignKey("ProductFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("ProductFeature");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.ProductFeature", b =>
                {
                    b.HasOne("Licensing.Domain.Entities.Product", "Product")
                        .WithMany("Features")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Licensing.Domain.Entities.License", "CurrentLicense")
                        .WithMany()
                        .HasForeignKey("CurrentLicenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Licensing.Domain.Entities.Customer", "Customer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licensing.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licensing.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentLicense");

                    b.Navigation("Customer");

                    b.Navigation("Plan");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.SubscriptionRenewal", b =>
                {
                    b.HasOne("Licensing.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Renewals")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Licenses");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.License", b =>
                {
                    b.Navigation("Activations");

                    b.Navigation("LicenseFeatures");

                    b.Navigation("LicenseLimits");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.Plan", b =>
                {
                    b.Navigation("PlanFeatures");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.Product", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Plans");
                });

            modelBuilder.Entity("Licensing.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Licenses");

                    b.Navigation("Renewals");
                });
#pragma warning restore 612, 618
        }
    }
}
